# Generated by Django 2.0.2 on 2018-02-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StuClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_system_demo.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('sex', models.IntegerField(max_length=1)),
                ('age', models.IntegerField(max_length=5)),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_system_demo.StuClass')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField(max_length=5)),
                ('sex', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_system_demo.Teachers'),
        ),
    ]
